version: "3"

services:
  minecraft:
    build: ./
    container_name: "paper_minecraft"
    environment:
      MEMORY_SIZE: "3G"
    volumes:
      - minecraft-data:/data
    ports:
      - 25565:25565

volumes:
  minecraft-data: